name: BuildAndTestAndPush
on:
  push:
    branches: main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git clone ibpv2-entity
        run: |
          date -R
