name: BuildAndTestAndPush
on:
  schedule:
  # 定时任务时间
    - cron: '43 * * * *'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git clone ibpv2-entity
        run: |
          date -R
